name: Performance benchmarks
on: [push, pull_request]
# Use this when the benchmarks are stable
# on:
#   push:
#     branches:
#       - master
jobs:
  cli_benchmark:
    name: CLI Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Clone and run on HTTPD
        run: |
          time git-churn -r https://github.com/andymeneely/squib.git -c 20f2063e678904ef34f1114a9d3bd4e71ab45a9c


  # benchmark:
  #   name: Performance benchmarks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-go@v1
  #     - name: Run benchmark
  #       run: go test -bench=. ./... | tee output.txt
  #     - name: Download previous benchmark data, if exists
  #       uses: actions/cache@v1
  #       with:
  #         path: ./cache
  #         key: ${{ runner.os }}-benchmark
  #     - name: Store benchmark result
  #       uses: rhysd/github-action-benchmark@v1
  #       with:
  #         tool: 'go'
  #          # Where the output from the benchmark tool is stored
  #         output-file-path: output.txt
  #         # Where the previous data file is stored
  #         external-data-json-path: ./cache/benchmark-data.json
  #         # Workflow will fail when an alert happens
  #         fail-on-alert: true
